### ISSUE TITLE
Crash going into 3rd person

### ISSUE THREAD

**Issue by DrakenStark** [hh79/gzdoomvr#1]
Brutal Doom is an awesome mod. It even has gone on to spawn it's own modding community. As big as it is, it actually runs amazingly great in VR! Problem though, as soon as you die in-game the game dies too (it crashes). I've also gone to test the mod's roll left/roll right buttons to also crash the game. It seems that whenever the camera tries to show the Doom guy character on screen, the game crashes hence the title of this issue. I'll keep playing regardless if this gets fixed, but the resolution of this issue would be greatly appreciated, make recording or streaming way less of a pain, and likely grant greater compatibility for other mods as well.

**Comment by hh79** [comment]
Thanks, please post which HMD do you have. I am using Oculus Quest via Virtual Desktop, so basically SteamVR sees it as a Rift S and I do not have a crash on dying in BD. However, definitely there is a bug, after dying head tracking stops - you can't see around you, when you turn your head view angle doesn't change. I plan to tackle this issue in future, but for now I have to upgrade this fork to the latest version of GZDdoom. While doing that, I fix only regression bugs.

**Comment by DrakenStark** [comment]
I have the original retail version of the Oculus Rift.

**Comment by seriousshuck** [comment]
I have WMR (Samsung odyssey plus) and can report the same.

**Comment by seriousshuck** [comment]
Played the new 4.1.3 update for a few hours tonight. Died A LOT. Game did not crash once. I'll keep you posted.

**Comment by hh79** [comment]
I close the bug, I have played BD couple hours with HP Reverb and Oculus Quest using Virtual Desktop but no crash on dying.
