### ISSUE TITLE
Movement on slopes?

### ISSUE THREAD

**Issue by seriousshuck** [hh79/gzdoomvr#10]
I don't know if this has been brought up, but movement on slopes is very buggy, it could be connected to the movement on moving platforms issue. I very much appreciate all the work you have done here. I just found this updated version today. I've been using the old one all this time. You've made some nice improvements! The HUD scaling is a nice touch!

**Comment by hh79** [comment]
Hi, thanks for a report, please post link to a wad which has this problem.

**Comment by seriousshuck** [comment]
Knee-Deep in ZDoom has a good spot to reference this issue in its first level. As soon as you start the game. 
http://kdizd.drdteam.org/download.php
Thank you.

**Comment by hh79** [comment]
Thanks, I have reproduced it.

**Comment by seriousshuck** [comment]
Thank you for the 4.2.4 release. For the information of anyone interested, the zmovement mod now works with gz3doom!  Unfortunately, I have tested movement on slopes using the zmovement mod and it still is buggy.  I appreciate all of your hard work nonetheless. I have plenty of other wads to enjoy why I patiently wait. Fixing the weapon jitter on stairs was a nice touch too, well done!

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/ec5830c43cac518d8b1f2690e327bdf4167ffab2
