### ISSUE TITLE
Invisible geometry in some maps when you have 3d weapon replacements

### ISSUE THREAD

**Issue by dxt121730** [hh79/gzdoomvr#13]
I noticed this when I updated to the latest released version, but it seems like on some maps, the entire world can go invisible if you have 3D weapon replacements.
![OculusScreenshot1587147821](https://user-images.githubusercontent.com/21349110/79601728-e69dfd80-80ae-11ea-8a3d-f81fa3732ee0.jpeg)
![OculusScreenshot1587147775](https://user-images.githubusercontent.com/21349110/79601730-e7cf2a80-80ae-11ea-9c1c-8ca4274ec8a7.jpeg)

The above shots show the same room with/without the included WeaponsForVR2.pk3 (I also was able to reproduce the issue with my custom 3D weapons for Brutal Doom 64, but figured I'd use the provided as a reference)

The map in question is this one, and was generated by Oblige, if that helps any.
https://www.dropbox.com/s/tq9k89xpa1b84g2/2020-4-15-2027_death_banished_den.wad?dl=0

I'm able to load and play it just fine on the previous 3.x.x version of this repo with/without the weapon replacements, so I assume it's something to do with the changeover to 4.x.x. (Though it works fine with the latest official GZDoom build, i.e. non-VR)

**Comment by hh79** [comment]
Hi, thanks for a report, it seems that rendering is now broken on maps which are using portals. Is this a case for this map too ? Anyway I am working on it and it will be soon fixed in 4.1.3.1 version.

**Comment by dxt121730** [comment]
That would make sense, I believe that's how Oblige does the 3D skybox which is used there. Good to know, thanks.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gz3doom/releases/tag/gvr4.1.3.1

**Comment by dxt121730** [comment]
Forgot to respond earlier, but that definitely fixed my issue, thanks!
