### ISSUE TITLE
Doesen't play OGG format music/sounds, maybe some other formats too

### ISSUE THREAD

**Issue by SinaelDOverom** [hh79/gzdoomvr#15]
Encountered in Golden Souls 2 where music of the 1st level and some sound effects don't play.
Music in OGG format, some sound effects in WAV and FLAC too.

Configuration otherwise similar to regular GZDoom, where all those sounds do play.

**Comment by hh79** [comment]
Hi, thanks for a report. Indeed music is missing in GS2, hope to have a fix soon.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/ff39362166e1c7f2c9f52a56b267bfc6018a93cd
