### ISSUE TITLE
Heretic-style Deep Water effect (TERRAIN lump setting) does not affect weapon position

### ISSUE THREAD

**Issue by SinaelDOverom** [hh79/gzdoomvr#16]
Heretic introduced a deep-water effect where player standing in water would "submerge" into it making his face closer to the surface. The feature is replicated in ZDoom via TERRAIN lump clipping setting.

In VR the visual height of the camera does change emulating the effect, however weapons remain unaffected and end up floating high above the point where they should be.

Easy to test on Heretic E1M1.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gz3doom/releases/tag/gvr4.1.3.2
