### ISSUE TITLE
Add option to lower camera when crouching/camera above ceiling

### ISSUE THREAD

**Issue by SinaelDOverom** [hh79/gzdoomvr#18]
Currently when player uses the crouch bind, the player can squeese through tight places as intended, but camera position doesen't change, so the playter view ends up being inside the wall, often being able to see through unintended geometry and overall being counterintuitive.

Suggestion: add an option for "simple crouch" like in Fallout 4/Skyrim VR - where if you press the crouch button, camera will lower to the apropriate height. (in GZDoom that's half the normal distance from the floor)

Another nice option would be to automatically lower the camera when it's above ceiling, ideally with customisable amount of units below ceiling.

Here's some screenshots and a test map where issue can be demonstrated/tested:
![20200426130843_1](https://user-images.githubusercontent.com/61930430/80303336-bb0ec780-87c0-11ea-84dc-e5737af581df.jpg)
![20200426130852_1](https://user-images.githubusercontent.com/61930430/80303337-bcd88b00-87c0-11ea-933b-1a2d3b713add.jpg)

[TestMapCrouch.zip](https://github.com/hh79/gz3doom/files/4535003/TestMapCrouch.zip)

**Comment by hh79** [comment]
Fixed crounching in https://github.com/hh79/gzdoomvr/commit/e31cd566f0898d7f369cb31399bb4087cd548b22
