### ISSUE TITLE
Suggestion: VR-interface hotspots/binds

### ISSUE THREAD

**Issue by SinaelDOverom** [hh79/gzdoomvr#19]
VR games often add inventory-like areas on the player body - waist, wrists, shoulders etc. that player can interact with, or place the items/weapons and later equip them by physically picking them up.

I understand this might be extremely tricky to do in GZDoom environment, so my suggestion is a bit different. 
Instead of making outright physical interaction it might be easier to make sort-of interactive hotspot areas that would invoke a bind (defined by player) when player puts their hand within such area and presses a dedicated button (most probably grip).
It would act akin to those inventory areas in modern VR games, but with much more customability on user part and significantly easier to code on developer part since no actual physical interaction betweween objects needed - just a check whether player hand is within one of those areas when they press grip (or whatever button they assign to it).
IMO would be better to associate rarely used letters with those areas - like YUIOPLKJHGBNM, so that the player would be able to assign their aliases/binds to them for various functions aside from weapon/item equip - they may also be used for more complex aliases, mod specific functions, next/previous inventory/weapon binds, using console comand and anything else normally bound to a button.

Areas I'd suggest:
2 behind each shoulder, 2 on the belt, 2 on the chest, 2 on the wrists, 1 behind lower back. Another good binding place would be touching Left and Right sides of headsets (without pressing the interact/grip button)- I've seen a few games using that kind of interaction for switching vision modes.

**Comment by codeflorist** [comment]
the Virtual Tactical Vest by @iAmErmac is probably exactly what you are looking for:
https://github.com/iAmErmac/Virtual-Tactical-Vest

it works with both GZDoomVR and QuestZDoom, and you can even smoke cigarettes.
