### ISSUE TITLE
Suggestion: Upgrade GZ3DOOM fork to 4.2over

### ISSUE THREAD

**Issue by ni1chigo2115** [hh79/gzdoomvr#20]
This is simply a suggestion for personal reasons.
Japanese is officially supported from GZDOOM 4.2. (4.1.3 can be converted to Japanese with MOD)

**Comment by hh79** [comment]
Hi, yes this fork will be updated to the latest version of GZDOOM, but please be patient.

**Comment by hh79** [comment]
I have updated my working branch to the latest 4.3.3, so far it looks good. I will soon release a new version after more testing is done.
