### ISSUE TITLE
Have option for voxel item models

### ISSUE THREAD

**Issue by iamcarrotmaster** [hh79/gzdoomvr#23]
Many mods like Project Brutality have addons where pickup items are made of voxels. They show up on the ground but dont look like that when held. There are mods for vanilla weapons what have models for the classic weapons what _look_ like they are voxels, but they are models. I was thinking it would be awesome that if you have item mode enabled it would choose the voxel model instead. of course it would be up to the voxel author to make sure it is pointing the right way.

**Comment by seriousshuck** [comment]
see here:

https://github.com/ajantaju/br_vr

**Comment by SinaelDOverom** [comment]
Wouldn't recommend using voxels in VR.
GZDoom's rendering transforms every voxel into separate cube model, which is much worse for performance than just a 3D model.

**Comment by iamcarrotmaster** [comment]
dont worry, the voxel project im working on uses obj models. much more performance friendly
