### ISSUE TITLE
Can i turn off haptic feeds ? For open composite  

### ISSUE THREAD

**Issue by StoniVR** [hh79/gzdoomvr#30]
Hello, so i like to use open composite with gzdoom this allows me to play this without steam vr on Oculus headsets, but since the haptic update. i get problems uncontrolled vibration in menu and everywhere so i forced to play with steamvr again and its runs a bit worse. so i was waiting a month and hoping open composite bring an update, but this is unfortunately not the case thats why i am asking here now. What is open composite ? here : https://gitlab.com/znixian/OpenOVR/blob/master/README.md

**Comment by hh79** [comment]
Hi, have you tried setting haptics level to 0 in VR Options ?

**Comment by StoniVR** [comment]
yes i try this at first its unfortunately not helping.

**Comment by hh79** [comment]
Check please the latest version https://github.com/hh79/gzdoomvr/releases/tag/gvr4.4.2, I've added an option for disabling haptics

**Comment by StoniVR** [comment]
oh thank you very much
