### ISSUE TITLE
Controller rotation affects weapon spread

### ISSUE THREAD

**Issue by bferguson3** [hh79/gzdoomvr#32]
Repro:
1. Set weapon mode to sprite only
2. Switch to shotgun 
3. Rotate motion controller on z axis (ie gangland style) 
4. Observe blast spread goes up and down instead of side to side 

Expected:
Motion controls shouldn't override weapon mechanics

**Comment by FolkSong** [comment]
I guess it makes sense physically. The real problem is that a shotgun should have a circular spread, not a flat line.

Or just stop trying to be gangster 😄

**Comment by bferguson3** [comment]
The problem is trying to hold your hand perfectly even, without a proper
cross hair or pointer, for a weapon that has a strange firing pattern. Game
design wise, it makes sense for it to go in a straight horizontal line, so
that means even in VR it should always go in a horizontal line.

Not 'trying to be gangster', just holding my hand normally, in a weapon
display mode that is impossible to tell with any precision where your hand
axes are.

I take to using the laser pointer mod because that's the only way I can
shoot reliably without the terribly ugly angled quad sprite mode.

**Comment by FolkSong** [comment]
I guess you're right, changing the spread would probably lead to balancing issues. Forcing it to be a horizontal regardless of gun orientation would solve the problem without creating new ones.

Just kidding with the gangster remark.

**Comment by FolkSong** [comment]
I just happened to notice, it appears Dr Beef (well-known developer of Quest ports) addressed this in his fork. Looks like he went with a random spread like my original suggestion.

https://github.com/DrBeef/gz3doom/commit/bf467012390cf7f3daf672f720c999ad7ff126e9

**Comment by bferguson3** [comment]
Very interesting. I'd like to see "pro" players and speedrunners (where
precision matters a lot) try it with different settings and see if it
changes the gameplay significantly.

**Comment by hh79** [comment]
4.5.0 contains fix from Dr Beef for a random spread, but I decided to revert this change. It is too random for my taste, especially when used with a chaingun.
