### ISSUE TITLE
Minimum requirements?

### ISSUE THREAD

**Issue by seriousshuck** [hh79/gzdoomvr#33]
I know this isn't a technical issue, and I apologize in advance if I am posting in the wrong area.

Would it be possible to add minimum requirements/recommended requirements to the readme? Would this run okay on a laptop with a GTX 1650 or 1650ti? Will it run on anything that claims to be "VR Ready"? I know doom is not the most demanding game out there, It's more the VR aspect that I am worried about running smoothly.

Thank you.

**Comment by Hyperlynx2** [comment]
What do you have to lose by just trying it?

**Comment by seriousshuck** [comment]
I was shopping for a new laptop and I wanted to know ahead of time. Ended up spending more than I wanted to and now I have a laptop with a 2070 in it. I just thought it would be nice for newcomers to know what the requirements are.

**Comment by hh79** [comment]
The general problem with gzdoom is a CPU bottleneck not a GPU, so probably GTX 1650ti should be fine. Perhaps it would help to reduce some visual options e.g. dynamic lighting. Saying this I have gtx 1080 with Ryzen 7 3700x and on many larger maps there are huge fps drops which make make playing in VR impossible.
