### ISSUE TITLE
controls not right with valve index

### ISSUE THREAD

**Issue by ContraVania** [hh79/gzdoomvr#34]
It seems like when i try to set up the controls from the menu, it gives them names it might give an xbox controller's buttons. It uses button names like Pad_Start, Pad_Back, Pad_A, Pad_X, Pad_Y, LShoulder, LTrigger. But I am using a valve index controller. I am not bothered by the names used, but I wonder if this is why I can't get it to work well. When I assign attack/fire to my right knuckle controller's A button, the button is labeled as RShoulder on the game, and so when I press my A button it will fire, but it also causes me to fire when I squeeze the right controller. I was playing Heretic and whenever I press up on my right thumb stick I walk forward correctly, but it also activates my flying item if I have one. I cleared out all the bindings to prevent buttons having multiple functions but I still think this gzdoom port is needing some fix for knuckle controllers.

Also, I can't assign a button to the thumb stick when it is clicked down, because whenever I press the thumb stick in a direction it behaves as though I am clicking it in. I tested my knuckle controller with Steam's software and it shows that I can move the thumb stick all around without the clicking function being activated so this should not be a problem with my controller.

**Comment by hh79** [comment]
Please check bindings for Index proposed in https://github.com/hh79/gzdoomvr/issues/5.

**Comment by ContraVania** [comment]
Regarding TIE-Interceptor's post, I think he gave directions based on older SteamVR software or something. I have to have the game running to edit the bindings using SteamVR, and I can save my settings to the workshop but it does not give me the option to search the workshop or load any other custom bindings. I thought I could search for the gzdoom bindings on the web page at [https://steamcommunity.com/workshop/browse/?appid=250820&searchtext=&childpublishedfileid=0&browsesort=textsearch&section=readytouseitems](url) but I got no results. 
I will instead play with keyboard and mouse since I don't think the given solution would make the thumb stick clicks be bindable and without that option I wont have enough buttons for Heretic. But thanks for replying so soon. :)

**Comment by codeflorist** [comment]
Check out the Community Binding "Index Controller Bindings" by gameflorist in SteamVR. It makes the maximum buttons available for binding in GZDoom. The A buttons and grip will be mappable independently. It also removes the "Use as Button" from thumbsticks to avoid firing click-events on moving sticks, which is exactly the problem with flying/walking you describe.

**Comment by LefTima** [comment]
> Check out the Community Binding "Index Controller Bindings" by gameflorist in SteamVR. It makes the maximum buttons available for binding in GZDoom. The A buttons and grip will be mappable independently. It also removes the "Use as Button" from thumbsticks to avoid firing click-events on moving sticks, which is exactly the problem with flying/walking you describe.

GZDoomVR is not on Steam, so you can't see community bindings that aren't yours.

**Comment by codeflorist** [comment]
> GZDoomVR is not on Steam, so you can't see community bindings that aren't yours.

hmm, dunno about that. i can see a different community binding by `ObeseCatLord`. maybe steam matches community bindings with the running .exe file?

but for all that don't see my bindings, here's the changes i made:
- map `A Button` Click to `Left/Right A Button` instead of `Grip Button` (so that A-buttons and grip can be mapped independently)
- remove the `Use as Button` mapping from both Thumb Sticks (to avoid firing click-event on moving sticks).
- add a `Use as Button` - `Click` binding for `Right Axis 2 Press` to the right trackpad (for an additional binding - only works once my pull request #79 is merged).
