### ISSUE TITLE
Win32 only code breaks Linux compilation

### ISSUE THREAD

**Issue by dikonov** [hh79/gzdoomvr#36]
The file _gzdoomvr-openvr_controller/src/rendering/gl/stereo3d/gl_openvr.cpp_ contains reference to two functions `I_StartupOpenVR()` and `I_OpenVRGetYaw()`, which are provided by a win32 only part of the source

```
make[2]: Leaving directory '/home/slava/RPM/BUILD/gzdoomvr-openvr_controller/BUILD'
make[2]: Entering directory '/home/slava/RPM/BUILD/gzdoomvr-openvr_controller/BUILD'
[100%] Linking CXX executable ../gzdoom
/usr/bin/ld.default: CMakeFiles/zdoom.dir/rendering/gl/stereo3d/gl_openvr.cpp.o: in function `s3d::OpenVRMode::SetUp() const':
/home/slava/RPM/BUILD/gzdoomvr-openvr_controller/src/rendering/gl/stereo3d/gl_openvr.cpp:1462: undefined reference to `I_StartupOpenVR()'
/usr/bin/ld.default: /home/slava/RPM/BUILD/gzdoomvr-openvr_controller/src/rendering/gl/stereo3d/gl_openvr.cpp:1471: undefined reference to `I_OpenVRGetYaw()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/zdoom.dir/build.make:7084: gzdoom] Error 1
make[2]: Leaving directory '/home/slava/RPM/BUILD/gzdoomvr-openvr_controller/BUILD'
make[1]: *** [CMakeFiles/Makefile2:1005: src/CMakeFiles/zdoom.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```
Deleting these with [gzdoomvr-delwin32refs.patch.txt](https://github.com/hh79/gzdoomvr/files/5635762/gzdoomvr-delwin32refs.patch.txt) allows to complete compilation. I am not sure yet, if the binaries remain functional after this. Please, fix!

**Comment by dikonov** [comment]
In every game the view is always directed UP. Upon launch gzdoom acts as if someone holds the down arrow pressed. The cursor and focus in the Doom, Heretic, Strife, etc. start menus rapidly moves from top to bottom and again.

**Comment by hh79** [comment]
Thanks, fixed

**Comment by hh79** [comment]
This method is needed for controllers to work, at least in Windows. I cannot help with Linux build, sorry.

**Comment by dikonov** [comment]
The code cannot be compiled while linux build references win32-only methods. They must be removed or placed under some ifdef. I have no idea what these two lines of code do and why controller support is linked to windows (I do not know C or C+). VR controllers work in Linux through native OpenVR-SteamVR or OpenXR without any windows libs.  I cannot test functionality of VR controllers yet (my VR rig is incomplete right now). It is possible that I_StartupOpenVR() and I_OpenVRGetYaw() are improperly tagged win32-only, if they are part of OpenVR. 

Gamepads in Linux certainly do not need the I_StartupOpenVR() and I_OpenVRGetYaw(), because they can perfectly emulate keyboard+mouse combo with qjoypad or antimicro, which always works.
