### ISSUE TITLE
Joypad misfunctions

### ISSUE THREAD

**Issue by dikonov** [hh79/gzdoomvr#38]
I have a Logitech F710 joypad. While its IR controller is attached to USB, gzdoom thinks that someone is constantly holding the UP arrow button. Detaching the Joypad controller stops this behaviour.

**Comment by hh79** [comment]
Could you please check how the joypad behaves in vanilla gzdoom ?

**Comment by dikonov** [comment]
The is no such problem in the vanilla gzdoom. I am able to run it and play with the joypad. 
The bug returns when I start gzdoomvr  without any other changes.

```
$ lsusb
Bus 002 Device 006: ID 046d:c21f Logitech, Inc. F710 Wireless Gamepad [XInput Mode]
```
I use qjoypad to configure it.

**Comment by hh79** [comment]
It seems that gzdoomvr changes for touch controllers somehow made gamepads broken. Unfortunatly I cannot fix this as I do not have a gamepad and also I don't have an HMD which works in Linux. The fact that gzdoomvr somehow runs in Linux I consider a miracle :)
