### ISSUE TITLE
inverted shooting for rocket lauchner, Plasma gun,Bfg9000 since new version

### ISSUE THREAD

**Issue by StoniVR** [hh79/gzdoomvr#4]
Hello i am really happy about your new Gzdoom versions, now with this version we can play Doom exp for example, but since this new version this 3 Weapons shot down when i aim up or up when i shot down. The other weapons and inputs seems to be to work. Thanks for your work. I will do videos where i celebrate you work that we can finally play some newer, more special mods. I am Stoni VR and i make Doom in VR videos since the first fisher release youtube.com/c/stoni and i stream often in doom groups on facebook doom mods in VR sessions. https://www.facebook.com/Stonivr-294800021298247/

**Comment by hh79** [comment]
Hi, thanks for a report. Somehow I haven't noticed this regression. It is now fixed in https://github.com/hh79/gz3doom/releases/tag/gvr3.7.2.1'.

Many thanks for promoting this fork. Please report if you find other issues. Unfortunately version 3.7 has changed a save format, so my old saves with test cases don't work anymore and I've basically tested it with pistol start only and I could miss some issues as a weapon pitch.

**Comment by StoniVR** [comment]
Hello thanks for fixing there are really a few issues or things that i want to talk about. First i was used that the game make pause when ever i go to menu so i dont waste a button for pause is there a way to change this back that game makes a pause when i press menu button ?  Than there is a old bug since the last fisher version that the left trigger is not bindable no use for secondary shot and is always set as +use button.  I use now really left trigger as use to safe a button. Than there is a unique laser sight (point) really fits to gzdoom vr with this mod u can even enjoy with 2d weapon sprites always good when u play heavy doom mods with complete change weapons or hexen something like that. https://drive.google.com/…/1OeR65vh-o1ttiAIK2MinN3D01J…/view So anyway thanks for doing this the doom exp session was really nice.

**Comment by hh79** [comment]
I have fixed pausing the game in https://github.com/hh79/gz3doom/releases/tag/gvr3.7.2.2. 
The controller binding code should be cleaned, left trigger is somehow hardcoded. I will look into it in the future.

Yeah, laser sight mod would be helpful, unfortunately the link is dead , I got 404 error.

**Comment by StoniVR** [comment]
>
> Yeah, laser sight mod would be helpful, unfortunately the link is dead , I got 404 error.

oh its not the first time that i copy and paste my link wrong https://drive.google.com/file/d/1OeR65vh-o1ttiAIK2MinN3D01JEqMowq/

**Comment by hh79** [comment]
Fixed
