### ISSUE TITLE
Game will not show up in HMD

### ISSUE THREAD

**Issue by TerabyteRex** [hh79/gzdoomvr#41]
I am using WMR and when i launch the game, inside steam "ready room" it has a floating icon that says waiting. The game i showing on my flat monitor with two renderings. Is there some setting/option i need to enable?

**Comment by marvtobi** [comment]
I am having the same issue, i could supply all kinds of steam logs and test things if need be.
The game starts fine, but steam and the vr headset just show the ready room with the floaty icon. Doom tracks hmd and controllers as well, just the vr view wont start in the hmd :/
Using a lenovo explorer, wmr for steam vr 1.2.485 and current steam vr 1.15.15.

**Comment by marvtobi** [comment]
Ok by pure luck i got it to work, i hope this helps others. It was the "Windows Mixed Reality for SteamVR Beta Update 1.2.485" That breaks things in GZdoomVR and also in other things like the Google Spotlight Movies.

After i switched the WMR for steam back to the normal branch, it downgraded the version to 1.2.444 and GZDoomVR as well as the other things load up just fine. I also switched my SteamVR back to the normal version as well, but that didnt help before, so i am 99% sure the WMR for SteamVR beta was the culprit.

**Comment by hh79** [comment]
The latest SteamVR version seems to work fine, at least with HP Reverb. One thing though, when you start gzdoomvr from FileExplorer when SteamVR is not running you have to change active application using alt + tab back to gzdoomvr because somehow it isn't active.
