### ISSUE TITLE
weapon sprite transparency issues

### ISSUE THREAD

**Issue by OmarLego** [hh79/gzdoomvr#44]
it seems like with some weapon sprites (example shown here is dox778's personalized addon for brutal doom) the transparency of the sprite does some weird wacky shit to other sprites i dont know how to explain it so heres a screenshot, it really bugs me so i hope it gets fixed.
![how2](https://user-images.githubusercontent.com/77136530/106556076-a4299e00-64d3-11eb-8526-b7816dc6624a.png)

**Comment by hh79** [comment]
Duplicate of https://github.com/hh79/gzdoomvr/issues/45
