### ISSUE TITLE
Index support

### ISSUE THREAD

**Issue by Slydk1982** [hh79/gzdoomvr#5]
Will there ever be index support for this mod? It has not worked for months now and every time there is a update I hope it will work, but never does. Its impossible to map keys..
Is this an oculus mod only??

**Comment by hh79** [comment]
Hi, this mod uses Steam OpenVR not Oculus SDK so in theory it should work with all supported HMD. I don't have access to Index so it is difficult to tell what is wrong but I have built again the version 3.7.2.1 against the latest OpenVR SDK, maybe it would be better. Please try and let me know if it helps
[gzdoom-vr 3.7.2.1 Index.zip](https://github.com/hh79/gz3doom/files/4338080/gzdoom-vr.3.7.2.1.Index.zip)

**Comment by Slydk1982** [comment]
Thanks for your hard work :) But it seems to be the same.. But I made custom binding for the index on steam, so now I can play. I can still not map my triggers, but every other key I can bind, so I made it work :)
But the keys/buttons I bind, seems to be Oculus keys, thats why I thought it was oculus only :)

**Comment by ajantaju** [comment]
Works out of the box with index here, triggers and all.

**Comment by ContraVania** [comment]
I suggest that the crosshair follows where the guns are pointing at instead of where the head is facing. 
Also, this works out of the box on my Index, thankfully!

**Comment by SinaelDOverom** [comment]
> I suggest that the crosshair follows where the guns are pointing at instead of where the head is facing.
> Also, this works out of the box on my Index, thankfully!

I use Laser Sight minimod from https://forum.zdoom.org/viewtopic.php?f=43&t=61079
It has good customisation options and also can draw trace beam where you aim (i use sparse particle dots and purple color)

Here's a bit altered version that works on skies and has increased max distance beyond initial 4000 https://www.mediafire.com/file/fuskyrnoarnfyzj/laser-sight-0.5.4.pk3/file

**Comment by TIE-INTERCEPTOR** [comment]
Hi, I own a Valve Index , and on the index controllers and I managed this weekend to set it up all so I can play without issues.

 I found that if I start a new install, and I go to steam overlay while in VR, select the game gzdoom on the overlay bar ( appears as a gray box without art in the middle ) and go to > controller bindings / load custom binding /  in there look for a published binding by some dude ( there is only 1 binding published so it's easy to see, it says on the comments, fix for index controllers for gzdoom ) that binding loaded will fix the trackpad and other things.

once that is done, you will have the main hand trigger for 'primary fire' as expected and the non-dominant hand trigger for 'use / open doors'

tips I found,  do not try to rebind the non-dominant hand trigger... as it will break and stop working.  ( ie, it can't be rebind, it only works as is... for some reason the non-dominant hand trigger works but if you try to rebind it it looses the bind and can't be re-done unless you delete the gzdoom config .ini file with the bindings and start again... it's odd but gz3doom doesn't like the non dominant hand trigger and trackpad, the rest of the buttons, joystick and grip work fine.

now you can rebind the controls with a bit of patience: This is my setup, that lets me play totally fine, and I don't feel like I miss anything or any action.
 I managed to remap the non-dominant hand joystick so up is kick and down is jump, I don't use left or right, as it's too sensitive and can miss fire , but they can be mapped if wanted , so you can have more button mappings available ( four )... Also I chose to turn my body in the real world, I play standing, so I don't need a turn option.

This are my bindings:

dominant hand :
 trigger = fire
 joystick > up = kick / down = jump,  press joystick = flashlight 
grip = next weapon
A = menu open
B = alt fire
non-dominant hand :
trigger = open / use
joystick > forward back and strafe motion , press joystick = toss grenade
grip = previous weapon
A= reload gun
B= crouch toggle ( some areas like low hight vents need to crouch , like in brutal doom maps, tip you won't see any difference, as in you won't be closer to the ground but other players can see you crouching, and your character is actually crouching, so you will be able to access vents and low Cealing areas. ) if I play Doom classic or Doom II y rebind this to  "quick turn" in my .ini file, to be able to do a 180 degree fast turn, that makes my life easier so I don't have to turn so much irl.

I'm attaching here my config .ini file If anyone finds it useful, be warned I'm left handed so you'll have to change the vr settings in game to right handed, and change the LStickUp=kickem > RStickUp=kickem etc, but it's easy and quite straight forward. ( I play brutal doom with kicks and jumps etc )

copy all the text inside of your gzdoom-***.ini file in gzdoom.
[gzdoom-yourname.txt](https://github.com/hh79/gz3doom/files/4575392/gzdoom-yourname.txt)
