### ISSUE TITLE
Weapon sprite transcluency is not fixed on "4.5" version.

### ISSUE THREAD

**Issue by dreadnaught40k** [hh79/gzdoomvr#50]
With the 4.3.3 version, it works totally fine, only on 4.5 has issue.
Using this https://www.moddb.com/mods/call-of-doom-cod-style-advanced-weapons-mod weapon mod.

I don't know how to fix it manually
by myself so posting it here.

**Comment by hh79** [comment]
It will be fixed in the next version

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/756c03c736f06fd12bf1d2d739e0378f77b2ae0c
