### ISSUE TITLE
Stream mode?

### ISSUE THREAD

**Issue by Hyperlynx2** [hh79/gzdoomvr#53]
(I just wanted to preface this by saying you've done a FANTASTIC job with this project. About a year ago I tried myself to update Fishbiter's work to the latest gzdoom, and wasn't successful, so I am full of admiration and appreciation for your efforts! Well done!)

I wanted to stream the game for some friends on Discord, but the screen I'd be sharing shows the two stereoscopic views. Is there a way to get the desktop application to show an ordinary view instead, while still getting the VR? (Not sure if this is a question or a feature request).

**Comment by tempanon1** [comment]
I'd try running gzdoomvr through something like Steam VR, which allows you to display a window that displays what's seen in just the right/left eye and stream that window rather than gzdoomvr itself.

**Comment by Hyperlynx2** [comment]
> I'd try running gzdoomvr through something like Steam VR, which allows you to display a window that displays what's seen in just the right/left eye and stream that window rather than gzdoomvr itself.

OH! Brilliant! It took me a while to figure out how to do this, but I see it's an option off of the Steam VR popup thingy itself!

Workaround works great for my purposes. Closing ticket :D
