### ISSUE TITLE
Slowdown and dropped frames in menu

### ISSUE THREAD

**Issue by Blizarre** [hh79/gzdoomvr#54]
Hi, GzDoom is awesome but I have a small issue in the menus:
When I am in the middle of a game, I can see on the steamVR perforamcne overlay that the rendering time is very short, (4 ms/frame), which is good enough to reach 90fps.
But as soon as there is a menu (startup menu, in game menu, or even the only startup splash screen), each frame takes 13/16ms and I start to get motion sickness.

I had that issue in your official build 4.5.0. I quickly ran some profiling with visual studio on `openvr_controller`, and I noticed that during the slow-downs, `gzdoomvr\src\common\rendering\gl\gl_framebuffer.cpp:OpenGLFrameBuffer::Swap()` was using 63% of the CPU time, while it was negligeable otherwise.

In the menu, most of the time is spent in OpenGLFrameBUffer::Update:
<img width="940" alt="bad" src="https://user-images.githubusercontent.com/66079/118398551-0fe1e200-b651-11eb-8c8f-588b6171bb8b.PNG">

Outside of the menu, everything seems alright:
<img width="536" alt="good" src="https://user-images.githubusercontent.com/66079/118398553-107a7880-b651-11eb-87c0-e59596784351.PNG">

Oculus quest 2, using AirLink. SteamVR, Nvidia 1060 6GB (driver 461.40), windows 10, OpenGL (Vulkan only gives me a black screen in VR)
I don't understand what could cause this?

**Comment by Blizarre** [comment]
Surprisingly it is not correlated with the complexity of the menu: I had this issue in vanilla Doom, doom2, doom2 + brutal, doom2 + brutal + vr guns + hd textures....

But somehow, the end of level screen (with the score and the secrets found) and the map are perfectly fine

**Comment by hh79** [comment]
Yes, it is known issue. I don't know if I am able to speed it up but I plan to move displaying menus to separate plane as it is in QuestZDoom. It will be a huge flat 2d screen so it should help reduce motion sick issues.  https://youtu.be/fLIouKzT4Lg?t=26

**Comment by hh79** [comment]
The performance issues - framerate was capped to 35fps was fixed in https://github.com/hh79/gzdoomvr/commit/20bb40d36388fe7d5c0d55927fc055b6d14e29b1
