### ISSUE TITLE
Oculus Quest 2 button mapping problem

### ISSUE THREAD

**Issue by Guardian9978** [hh79/gzdoomvr#55]
I'm using Oculus Quest 2 over Air Link mainly because questzdoom keeps crashing with all my mods. The problem I'm running into is the buttons are labeled wrong somehow...

So far what I've seen is 
A button on the right controller shows up as Pad_B
B button on the right controller shows up as Pad_Back
Right Stick Button shows up as Pad_Y
Left Stick Button shows up as Pad_X
Y button on left controller shows up as Pad_Start
X button on left controller shows up as Pad_A
The 2 trigger buttons and the left Oculus button can't be rebound.

**Comment by mrjertop** [comment]
The dev has announced in another issue that a rework of the controls is underway. In addition to the issues you note above, some of the bindings at this point appear simply to be hard set and can not be modified. I would probably wait for the control overhaul announced here:

https://github.com/hh79/gzdoomvr/issues/58#issuecomment-866723985
