### ISSUE TITLE
Railgun attack needs to use weapon offset instead of head position

### ISSUE THREAD

**Issue by iAmErmac** [hh79/gzdoomvr#56]
Functions like A_RailAttack or A_CustomRailgun uses head position to fire railgun attacks (ie. fires from head). It needs to fire from the weapon itself, ie. needs a fix to use weapon offset instead.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/216b0d8cb61e6dcb9efc666c63dec3d098295a45
