### ISSUE TITLE
Weapon overlay alpha transparency doesn't work properly

### ISSUE THREAD

**Issue by iAmErmac** [hh79/gzdoomvr#59]
Alpha transparency on weapon overlay png (called by A_GunFlash or A_Overlay) doesn't have proper transparency and produces a hard edge on the opaque part while in regular GZDoom overlay shows proper translucency levels. The problem in GZDoomVR is the translucent parts are not visible at all but only the opaque parts are, so semi-transparent parts of a png are removed on the final rendering. Muzzle flashes on 3D weapons will look way better if this problem is fixed.

**Comment by Hyperlynx2** [comment]
It would be super duper great if this one gets fixed.

Possibly it only affects weapons introduced by wads, but it's a big problem.

edit: although, https://github.com/ajantaju/br_vr is viable alternative for me, since I play with a (variation on) Brutal Doom.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/756c03c736f06fd12bf1d2d739e0378f77b2ae0c
