### ISSUE TITLE
[Suggestion] Hud size/distance settings.

### ISSUE THREAD

**Issue by ajantaju** [hh79/gzdoomvr#6]
Firstly i must congratulate you for the magnifient job you have done!
Now we can have nice Hud mods that have radars and other fancy stuff like PBR materials.
I just tested https://www.moddb.com/mods/brutal-doom/addons/catsvisor-hud-12-for-bd21-more-widescreen and it worked just fine but the text was really tiny and pretty far away. So maybe when you have reached parity with the newest gzdoom, could you look into some additional features like hud placement/size/distance?

In the meantime i should look into PBR materials and update the vanilla weapons 3D models, so you can include them into this mod if you so choose to.

**Comment by hh79** [comment]
Thanks. I have added options for HUD positioning in the latest version https://github.com/hh79/gz3doom/releases/tag/gvr3.7.2.2

If you update 3D models sure I will add them. Are you by chance author of BrutalDoom 3D weapon pack ?

**Comment by ajantaju** [comment]
Indeed i am.

**Comment by hh79** [comment]
Thank you, without it I would not have motivation to test Brutal Doom. Can I perhaps put your weapon pack into releases zips ? I would of course add proper credits to README.

**Comment by ajantaju** [comment]
And you have inspired me to continue my work. I'm working on tweaking some [animations, models and materials.](https://i.imgur.com/4dHAMRF.jpg) I'll do the vanilla doom weapons first so you can incorporate them to latest release or add them to release page. You could also add link to the [Brutal Doom VR weapons git](https://github.com/ajantaju/br_vr) in the README, if you so wish.

**Comment by hh79** [comment]
It looks amazing, please continue your work. I did not know that GZDoom has these advanced capabilities.

**Comment by ajantaju** [comment]
I've finished the vanilla weapons: [HDVRweapons.zip](https://github.com/hh79/gz3doom/files/4378108/HDVRweapons.zip)
You can add this to release page, or the README. No need to unzip, just drop into [ZDL](https://github.com/lcferrum/qzdl/releases).

PBR supported if mixed with mod/maps that have dynamic lights, for example: [Dark Encounters](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/drkenctr) or GZdoom included lights.pk3 that enables them to vanilla levels decorations/fireballs etc.

I'll continue to work on the Brutal Doom version now.

**Comment by hh79** [comment]
Thanks, it works great. I have put links to both weapon packs in the README.

**Comment by hh79** [comment]
Fixed
