### ISSUE TITLE
[BUG] Can't stop myself from jumping with the right analog stick on Index

### ISSUE THREAD

**Issue by PsYchitOut** [hh79/gzdoomvr#65]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Relevant hardware info

Intel 11900k, rtx 3080, 64 gb ddr4-3200, Valve Index

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I feel like there's a better place for this but I can't seem to find much online in the way of fixing this issue. For some reason by default turning with the index controller makes the character jump repeatedly. it's only when push the analog stick to the outermost point in any direction. 

I'm assuming it's a holdover from the Vive controls but I can't figure out how to change it. The steam VR menu just has it listed as analog right (or something along those lines) any attempt to manually change the binds in the settings  just makes things worse, I can't figure out how to delete binds you made by mistake in the menu and I don't really know what commands I should be putting in to edit the ini manually.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play gzdoomvr with index controllers.
2. Push the right analog stick all the way in any direction
3.jump up, jump up and get down.

### Your configuration

```ini
I'm at work right now so I can't access it by it's the default in found right after extracting the game. I'll forward it when I get home if you need it.
```

### Provide a Log

N/A

**Comment by PsYchitOut** [comment]
Hello I recently tried to give this a second try and figured out what the issue is. The binding menu does not seem to be able to differentiate between an analog click and pushing a direction. So say if you have jump bound to your right analog click any time you use that stick to turn it will trigger for you to jump over and over again. It also does not seem to understand the difference between the touch pads and the analog sticks either.

**Comment by codeflorist** [comment]
Try out the Community Binding "Index Controller Bindings" by gameflorist in SteamVR. It makes the maximum buttons available for binding in GZDoom and also removes the "Use as Button" from thumbstics to avoid firing click-events on moving sticks, which is exactly the problem you describe.

**Comment by hh79** [comment]
Default bindings were reworked, please download the latest 4.13.2 version
