### ISSUE TITLE
[BUG] Unable to turn Multisampling off

### ISSUE THREAD

**Issue by WiggyWest** [hh79/gzdoomvr#68]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Relevant hardware info

RTX 2080 8700k 16GB ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Unable to disable multisampling when in VR. 
If headset is not detected in Steam then the option to toggle multisampling: off >2x> 4x 8x etc is available. 
When in VR mode and headset detected clicking multisampling to go below 2x will jump back to 4x, no off option available. 

Tried GZDoomVR 4.6.1, 4.7.1 Latest Nvidia Drivers, Older Nvidia drivers, Forcing AA off in Nvidia Control Panel. Disabling AA in NVidiaInspector. 
Using gl_multisample=1 in config file has no effect, Multisampling remains on.

Noticed a reference to possibly similar related bug in normal GZDoom posted here: https://forum.zdoom.org/viewtopic.php?f=7&t=51616 
"I somehow suspect this is connected to the recent submission with new stereo 3D modes. That was also causing some issues with Linux."

### Steps to reproduce the behaviour.

1. Launch GZDoomVR 4.7.1 with headset activated 
2. Go to display option and try to switch multisampling off
3. Can only choose 2x 4x 8x 16x 32x etc. Off is no longer an option.

### Your configuration

```ini
https://gist.github.com/WiggyWest/07b0ae1a706d395130c5af931169308e#file-gzdoombd01a-ioni
```

**Comment by iAmErmac** [comment]
I tried commenting off these lines https://github.com/hh79/gzdoomvr/blob/openvr_controller/src/rendering/gl/stereo3d/gl_openvr.cpp#L1304-L1305
But honestly I don't see any difference between multisample x2 and off state. Maybe turning it off has consequences (like breaks something somewhere?) or you may get random white pixels. also gpu memory usage stays the same when it's off or set x2. i'll have to dig deep to confirm but I guess multisample x2 is applied regardless when it's off?

**Comment by WiggyWest** [comment]
Hi iAmErmac appreciate you confirming the issue was not just on my end. Thanks for your great mod releases too!

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/65069dda5d2af2409648cc6fb648a6c11075fa41
