### ISSUE TITLE
[BUG] Incompatibilty with SteamVR/ALVR - All menus completely stop transmission of frames

### ISSUE THREAD

**Issue by zulc22** [hh79/gzdoomvr#71]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro (AMD64)

### Relevant hardware info

Ryzen 5 4600H APU + AMD RX5600M dGPU (Dell G5-5505)

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Opening the menu completely stops data transfer in ALVR. Maybe something to do with the mouse unlocking?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Use ALVR to connect your computer and Quest 2
2. Open the menu (or be stuck in one at startup, e.g. not adding +map map01 or something to your command line)
3. Be frustrated

**Comment by zulc22** [comment]
https://user-images.githubusercontent.com/54846511/177139724-98d8f317-4d48-42a5-af59-ee7fc9de1508.mp4

**Comment by hh79** [comment]
I could not get ALVR to work with gzdoomvr. That was 2 years ago, maybe there was some improvements in ALVR since then but I am not going to test it. I am using Virtual Desktop or Quest Link and they work fine.
