### ISSUE TITLE
[Feature]  Snap turn

### ISSUE THREAD

**Issue by havetc** [hh79/gzdoomvr#74]
### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

Smooth turn can be nausea inducing in VR, and I far as I know it is the only option available to turn.

### Describe the solution you'd like

I'd like to have an option to select between snap turn and smooth turn. I already started to look at the codebase, and that doesn't look like a big change to implement, so I'll try to do it once I'll have the compilation setup configured.
I just post this feature request  to have some feedback, and to ask you if it's not already an option that I've just missed :)

**Comment by havetc** [comment]
I'm kinda fighting with the build environnement. As there is no doc about it, it is really tedious to setup.
It is required to have an external installation of OpenVR ? I have an error with it, and in contrary to dependencies like Zmusic or bzip2, it doesn't seems to be within the repository.
Having the info about what compiler do you use could at least give some  idea about what may be a supported toolkit or not.

**Comment by codeflorist** [comment]
> I'm kinda fighting with the build environnement.

i was in the same boat. here is what it did (windows 10):

prerequisites:
- CMake (https://cmake.org/download/)
- Visual Studio 2022 with C++ workloads
- current release of OpenVR source (https://github.com/ValveSoftware/openvr)

steps:
1. launch cmake
2. set `Where is the source code` to gzdoomvr source
3. set `Where to build the binaries` to an empty directory.
4. press `Configure` at the bottom left, set generator to installed Visual Studio Version and click `Finish` and let CMake do it's thing.
5. a list of (red) variables should appear.
set `OPENVR_SDK_PATH` to the OpenVR source.
also you might want to change `ZDOOM_EXE_NAME` to `gzdoomvr`. 
6. click `Generate` and let CMake do it's thing. no variables should be red anymore.
7. close cMake
8. navigate to the selected build-directory and open `GZDoom.sln` in Visual Studio.
9. select `Build ALL_BUILD` in Build-menu. this should build gzdoom inside the `Debug` (or `Release` - if your build target is `Release`) subfolder of your build folder.
10. Copy the files `zmusic.dll` and  `openvr_api.dll` from a current `gzdoomvr` release inside this folder (dunno how to get these to build with the rest).

that should do the trick.

**Comment by havetc** [comment]
Thanks @codeflorist ! In the end once I used Visual studio (I started with Mingw, not a bright idea... ) it got far easier. I just got some trouble mainly with precompiled headers which wouldn't want to generate, but after a bit a tinkering I got it working. I think I have ninja as a generator, maybe setting it to visual studio as you say would have avoid me that problem!

Anyway the feature is almost done, I just need to fix a weird issue: when I try to turn an amount of degree, it turns almost the right amount but not quite. So if you make a full turn (4 time 90°), in the end you're not perfectly aligned with your starting position, which can be a bit disorienting.

PS: I think your comment is very usefull, and would deserve its place in the Readme. Maybe I'll add those instructions later in a pull request, but feel free to do it first if you want :)

**Comment by codeflorist** [comment]
> PS: I think your comment is very usefull, and would deserve its place in the Readme. Maybe I'll add those instructions later in a pull request, but feel free to do it first if you want :)

yeah, i do have that planned, in addition to reworking/improving the mods-section.

**Comment by havetc** [comment]
#86 This has now been implemented for a while and is waiting for a merge

**Comment by havetc** [comment]
UP, if someone with write access could kindly have a look at #86 , I implemented Snap turn a while ago and it should be quite straightforward to test it and validate it, and I'd be happy to add any modification if required :)

**Comment by Maacciieejj** [comment]
Hi, can I tur on snapturn somewhere on menu in gzdoomvr? I'm normal user, not programmer :)

**Comment by havetc** [comment]
Hi @Maacciieejj , not yet the feature has been implemented but is waiting for approval/merge. At the moment you won't find it in the release you can download here.

**Comment by Maacciieejj** [comment]
Do you know approximately when this will be? Because I want to play with my brother from snaptyrning so he won't get discouraged :) GZdoomvr has the option to play online just like regular gzdoom?

**Comment by hh79** [comment]
Implemented by https://github.com/hh79/gzdoomvr/pull/86

**Comment by Maacciieejj** [comment]
Jea! Thanx!
