### ISSUE TITLE
[BUG] The game keeps spinning around

### ISSUE THREAD

**Issue by sstarbright** [hh79/gzdoomvr#76]
### GZDoom version

gzdoomvr 4.8.2

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

RTX 3070, Valve Index

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The first time I tried gzdoomvr, it seemed to work fine. Later attempts at launching the game would make my view spin around repeatedly.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. I don't know

**Comment by havetc** [comment]
Do you have an unused controller or joystick plugged in? In other games that can sometimes cause the exact same issue as you describe.

**Comment by sstarbright** [comment]
Ah, that would do it. Thank you!
