### ISSUE TITLE
[BUG] Cannot bind LTrigger to any action

### ISSUE THREAD

**Issue by knowsshit** [hh79/gzdoomvr#77]
### GZDoom version

4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

x64 21H2

### Relevant hardware info

Oculus Quest 2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

LTrigger is mapped to +altattack as default, but it does not respond. I tried changing it to +use but it doesn't react either. Other buttons on the controllers seems to work fine.

I discovered this when trying to run Brutal Doom and using the fists. Right clicking the mouse still works for alternate fire, but LTrigger (the trigger on the left VR controller) does not seem to trigger anything, even if manually binding it to +attack or +use or other actions manually in the console or config files. Trying to bind it using the menus does not register when I press LTrigger. The menus are still waiting for a button press. Other controller buttons will register fine.

PS: Would it be possible for GZDoomVR to work with mods that have dual wielding (one weapon in each VR hand)? Or is it only for one weapon/hand?

### Steps to reproduce the behaviour.

1. Run GZDoomVR in SteamVR with Oculus Quest 2 and load any game.
2. Try to change the button for an action. Nothing happens if LTrigger is pressed.
3. Alternatively run `bind LTrigger +attack` in the console or edit config files and see that LTrigger does nothing in the game

**Comment by codeflorist** [comment]
the left trigger is bound to `Joy4`. unfortunately it cannot be mapped in the menu, but only by editing the ini-file.

so manually setting `Joy4=+attack` in the `[Doom.Bindings]` section of your `hzdoomvr-*.ini` should do the trick.

furthermore, the right trigger, which also cannot be mapped using the menu is hard-bound to `RTrigger`.

**Comment by muizzsiddique** [comment]
Can you or someone else list what the other buttons on an Oculus Touch controller are named so we can add them to the ini? My X button (Left application button) doesn't seem to do anything nor does left stick press or right stick press. I would also like to reconfigure the controls in general.

**Comment by knowsshit** [comment]
Hi!

I made a table showing Oculus Touch controller buttons, the name GZDoomVR uses for those buttons, and what actions I have bound to them (for mostly playing Brutal Doom).

Note that the movement of the left and right stick are mapped as joystick inputs, and I have not actually mapped them to +forward, +back, +moveleft, +moveright, +left and +right.

A table copy pasted from Excel (that somehow kinda works in github) is included below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/THOMAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/THOMAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Friendly | GZDoomVR | Action | Automap
-- | -- | -- | --
LTrigger | Joy4 | +altattack |  
LS-Left | Axis1Minus | +moveleft |  
LS-Right | Axis1Plus | +moveright |  
LS-Down | Axis2Minus | +back |  
LS-Up | Axis2Plus | +forward |  
LS-Press | Pad_X | kickem |  
Y | Pad_Start | togglemap |  
X | Pad_A | +use |  
LGrip | LShoulder | weapprev | +am_zoomout
Menu |   |   |  
  |   |   |  
RTrigger | RTrigger | +attack |  
RS-Left | Axis3Minus | +left | +am_panleft
RS-Right | Axis3Plus | +right | +am_panright
RS-Down | Axis4Minus |   | +am_pandown
RS-Up | Axis4Plus | flashlightswitch | +am_panup
RS-Press | Pad_Y | Reload | am_toggletexture
B | Pad_Back | menu_main |  
A | Pad_B | grenadetoss | am_togglefollow
RGrip | RShoulder | weapnext | +am_zoomin
Oculus   menu |   |  



</body>

</html>
