### ISSUE TITLE
Project Brutality Code Mismatch 

### ISSUE THREAD

**Issue by waefrebeorn** [hh79/gzdoomvr#8]
Scripting Language is outdated. Possible to port newer version?

Script error, "Project_Brutality-master.pk3:zscript.zc" line 1:
Version mismatch. 4.1.3 expected but only 3.7.2 supported

**Comment by hh79** [comment]
Hi, I am testing now version 4.1.3, the release will be very soon. Unfortunately it seems that current version of  Project Brutality requires the latest version of GZDoom, 4.3.  I hope to eventually sync releases with upstream, but it will take some time.

**Comment by waefrebeorn** [comment]
Thank you so much for your continued contribution. Seeing even the potential to have it updated is very inspiring. I updated the GZDoom forum post as well highlighting your update. 4.1.3 should run older versions of Project brutality and I will report back on that later tomorrow. My next concern will be with Windows Mixed Reality button remapping issues for mods that use non standard button configurations. (IE. Project Brutality, Brutal Doom, Golden Souls 2 and 3) It seems the triggers and various presses don’t work but analog sticks do. I can work with you to recreate and document any bugs with this to help with WMR support for your fork as it is the most up to date. I also have a XBone wired controller and will be seeing if controller remapping for those controller paths is similar as they identify as “triggers” in win 10.

**Comment by hh79** [comment]
Yes, please report any issues with WMR. I have bought recently a WMR headset and it seems working just fine, but I usually play WADs without mods.

**Comment by waefrebeorn** [comment]
How are you remapping the keys? When I go into the menu and select remapping, some buttons do nothing and I can’t map triggers and such.

**Comment by hh79** [comment]
Project Brutality works with the latest release but performance is poor. Remapping the keys is currently bit broken, I hope to port some improvements from QuestZDoom e.g add second function on a grip.
