### ISSUE TITLE
[BUG] Weapon sprite transparency is not working above 4.3.3 version.

### ISSUE THREAD

**Issue by dreadnaught40k** [hh79/gzdoomvr#80]
### GZDoom version

GZDoomvr 4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

5800x / 3090ti / 32gb 3200mhz ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GZdoomVR 4.3.3 has the weapon sprite transparency as this video, so I can see through it
but the version above 4.3.3 does not have this feature, this makes me still stick with 4.3.3.

https://www.youtube.com/watch?v=rApsBh16lEU [4.3.3 Sprite transparency working version]
*Description has the wad list.

Seems the other version doesn't have the feature of 4.3.3, please renew this thing
for later versions so I can apply some wad that requires a higher version than 4.3.3.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by Zod1234** [comment]
this is still an issue.  playing the mod 'Siren' and i can't see the enemies if I'm holding the gun in front of me.

**Comment by hh79** [comment]
It will be fixed in the next version.

**Comment by hh79** [comment]
Fixed in https://github.com/hh79/gzdoomvr/commit/756c03c736f06fd12bf1d2d739e0378f77b2ae0c
