### ISSUE TITLE
[Feature] Supporting or synchronizing with gzdoom v4.9.0

### ISSUE THREAD

**Issue by Donatello-za** [hh79/gzdoomvr#87]
### GZDoom version

GZDoom v4.9.0

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Is your feature request related to a problem? Please describe.

I would like to try and get the Wolf3D-TC-3.0 (Wolfenstein 3D Total Conversion) to work in gzdoomvr but it requires GZDoom v4.9.0 or later to work.

### Describe the solution you'd like

Synchronizing current project to version 4.9.0 of GZDoom if possible.

### Describe alternatives you've considered

I don't know the amount of work involved but can perhaps try and do it myself.

**Comment by hh79** [comment]
I have already merged 4.9.0 changes into gzdoomvr. Proper 4.9.0 release will come later. I need to try to fix some bugs first.
