### ISSUE TITLE
[BUG] Sound not working in 4.11.3 Release

### ISSUE THREAD

**Issue by guitardz** [hh79/gzdoomvr#89]
### GZDoom version

4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Pro

### Relevant hardware info

AMD Ryzen 7 5800X, RX 6700 XT, MSI - B550 GAMING PLUS, Rift S

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

There is no sound in game at all.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start game.
2. There is no sound.

### Your configuration

```ini
https://gist.github.com/guitardz/d6f40c61636b02a9244b13e1fa9dca1c
```

**Comment by hh79** [comment]
Please download it again. First zip was broken. If that does not help. copy from an older version of gzdoomvr zmusic.dll and openal32.dll

**Comment by guitardz** [comment]
Thanks, copying those dlls worked.
