### ISSUE TITLE
[BUG] Openal32.dll error, missing audio, doesn't properly open in VR, constantly spinning

### ISSUE THREAD

**Issue by gregest** [hh79/gzdoomvr#90]
### GZDoom version

4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 22H2

### Relevant hardware info

I5 4690, GTX1650, 16GB Ram

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I downloaded gzdoomvr, extracted it, placed doom2.wad in the folder from a legal doom2 purchased copy. When I try to open it, either PC or inside from my headset I get an error about openal32   

![gzdoomvr_2023-12-16_19-06-42](https://github.com/hh79/gzdoomvr/assets/56032903/74350f5e-a002-4470-b14a-3d484ca5337a)
(rough translation: openal32 was not designed for windows, or contains errors. Try reinstalling or contacting the author of the software, error code: 0xc000012f.    

I'm also having an issue where there is absolutely no sound, console mentions SoundInit failing, using NoSound. Searching around it should be fixed by a redownload based on a report a few days ago but didn't for me.    

![VirtualDesktop Android-20231216-185603](https://github.com/hh79/gzdoomvr/assets/56032903/3418a287-4fbe-49ee-a23f-7cb76435b196)
This is what I mean by "doesn't properly open in vr", it just gives me the view of my screen rather than being "in" the game, this is in Virtual Desktop using VDXR as the OpenXR runtime.  

And constantly spinning is well, constantly spinning.     

I tried reinstalling it 4 times now, same results every single time. I tried a purely vanilla save with no extra wads nothing, error. I tried running through ZDL with a few mods, ZDL is just a launcher for doom that makes it easier to use multiple mods at the same time, no openal32 error however all the same issues persist

![ZDL_2023-12-16_19-29-03](https://github.com/hh79/gzdoomvr/assets/56032903/afb6e075-af5f-4549-8286-fc4befc40873)
The mods in question I tried to use

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Install GzdoomVR
2. Open
3. Error

### Your configuration

```ini
I don't seem to have a separate ini file for GZDoomVR, only one for the regular desktop GZDoom which isn't being used by GZDoomVR because all my settings were default when opening GZDoomVR.
```

### Provide a Log

[log.txt](https://github.com/hh79/gzdoomvr/files/13693551/log.txt)

**Comment by hh79** [comment]
Please download release 4.11.3 again.

**Comment by ReverVR** [comment]
I have an looks like error with sound

Download again but sound error persist

Error: "Could not find patch set My Route//soundfonts/gzdoom.sf2"

Fluidsynth error

And file is in the correct route

¿Solution?

Thanks

**Comment by hh79** [comment]
Try maybe to copy from an older version of gzdoomvr libflluidsynth.dll , libflluidsynth64.dll, zmusic.dll. openal32.dll. If that does not help, try to download an official release of gzdoom 4.11.3 and then copy there gzdooomvr.exe. gzdoom.pk3, game_support.pk3.

**Comment by ReverVR** [comment]
Hi

I try both solutions but not work. First same error. Second only  play not vr mode

Thanks

Wait other solutions

Thanks

**Comment by ReverVR** [comment]
Hi again

Testing gzdoomvr 4.8.2 works great for me

Testing gzdoomvr 4.9.0 and 4.11.3 dont work. Black screen and hear sound but not enter vr mode or audio issues

Wait you can resolve that

Thanks in advance

**Comment by hh79** [comment]
Oh, that's not good. I haven't made any changes to the sound-related code, and version 4.9.0 worked perfectly for me for a year. You might want to consider resetting the settings to default. Starting from version 4.9.0, there's a global gzdoomvr.ini file located in Users/[UserName]/My Games/GzdoomVR directory. Try deleting or moving it from this directory, and then try running it again.

**Comment by ReverVR** [comment]
Hi

Delete .ini and GZDOOMVR 4.9.0 works great but GZDOOMVR 4.11.3 already black screen. Hear sound but not display

¿Solution or fix?

Thanks

**Comment by ReverVR** [comment]
Hi again

GZDOOM VR 4.11.3 work now

Thanks for all your job

**Comment by gregest** [comment]
unfortunately didn't help for me, I deleted my gzdoom.ini and it made no change, I also redownloaded it yet again with no luck.   

I forgot to mention that if I start it directly through steamvr instead of virtual desktop, it does "boot up" but it's entirely black, I can hear the sound in the background and I can click things but it's black
![59bf758f139c97890942722236691d40](https://github.com/hh79/gzdoomvr/assets/56032903/b088c1ae-82fa-42aa-bffd-cc8a6b49a2b1)

**Comment by flabberghastio** [comment]
same here 

> unfortunately didn't help for me, I deleted my gzdoom.ini and it made no change, I also redownloaded it yet again with no luck.
> 
> I forgot to mention that if I start it directly through steamvr instead of virtual desktop, it does "boot up" but it's entirely black, I can hear the sound in the background and I can click things but it's black ![59bf758f139c97890942722236691d40](https://private-user-images.githubusercontent.com/56032903/292333562-b088c1ae-82fa-42aa-bffd-cc8a6b49a2b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODgwNDUsIm5iZiI6MTcwMzI4Nzc0NSwicGF0aCI6Ii81NjAzMjkwMy8yOTIzMzM1NjItYjA4OGMxYWUtODJmYS00MmFhLWJmZmQtY2M4YTZiNDlhMmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDIzMjkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMGFjZGMwNmE5MmU5MmYxNTc0NjZkZTVkMWNiYjgwY2UxZGE5NTNiOWRmYWEyOWU3MThjY2MxODFkYThlMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9S_dB4HSqkyuGvL50Dh2joOmbtHXBBfOi7P77nmdTsI)

**Comment by doomgtr** [comment]
I also have no sound in 4.11.3, there are no other errors. All previous versions work fine.

**Comment by doomgtr** [comment]
When deleting zdoom.ini, I also get a black screen.

**Comment by Doom2VoxelVRLover** [comment]
BLACK SCREEN ISSUE = probably Vulkan.  Edit your INI file line "vid_preferbackend=0" (OpenGL) instead of "vid_preferbackend=1" (which is Vulkan).  Worked for me on Win10 and 4080, latest driver 546.65.  Default INI file seems to select Vulkan too, which is why you are getting a black screen when you delete the INI.

A different issue I now have with this version is total crash when in game and trying to change weapon models from sprite only to anything else like fat sprite.  Was fine on old version 4.9.0.  My workaround is to use the HD VR weapons mod, but I kinda prefer the old school look in 3D.

**Comment by gregest** [comment]
Ah yeah, swapping to opengl instantly fixxed my issues and everything seems to be working. I haven't tested your crash though as I use the voxel model weapon pack mod so I guess I'll leave the issue open. Thanks!

**Comment by hh79** [comment]
Please download the latest version 4.13.2. The sound libraries have been updated to match the latest GZDoom, and the default backend has been set to OpenGL.
