### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by Massacher** [hh79/gzdoomvr#91]
I got the latest version. But when I attempt to launch it, it freezes with the console window still showing. Does it matter what order I load the other files in? I have a batch file with this in it:
gzdoomvr.exe -file WeaponsForVR.pk3 -file DoomMetalVol5.wad -file VoxelDoom_v_2.3.pk3
I have also tried just running gzdoomvr.exe on its own with the same result. It freezes.
That's as far as it gets. I can see in task manager that its not responding.
![GZDoomvr 4 11 3 freeze](https://github.com/hh79/gzdoomvr/assets/131346017/82e9a874-8544-43fc-8ca5-e141116c21c2)

And it doesn't matter if I have SteamVR open or not. Same result. Though when I don't have it open and attempt to launch the game it will attempt to open up SteamVR and launch anyway. But I just get the empty grid room.

I have also tried [this](https://www.reddit.com/r/oculus/comments/qctc6h/comment/hhliump/?utm_source=reddit&utm_medium=web2x&context=3) but there is no openvr_api.dll in the download. But there are other .dll's:
![image_2024-01-30_184019138](https://github.com/hh79/gzdoomvr/assets/131346017/8e35cb2e-ca38-4846-ba42-4a492279f19e)

**Comment by Massacher** [comment]
bump

**Comment by hh79** [comment]
If you are using a version older than 4.12.2, please select the OpenGL backend.
