### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by codenamehotline** [hh79/gzdoomvr#93]
### GZDoom version

gzdoomvr 4.1 1.3

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

windows 11

### Relevant hardware info

amd ryzen 5 562GU 

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

when i launched it it shows a screen of the game but not in vr it's a black screen
![Screenshot 2024-03-18 211051](https://github.com/hh79/gzdoomvr/assets/96748149/d2913c51-fc56-4e2c-b11f-3d5bb1db3b74)
![54d19cf473f71aaf0c14f2ae2c01d3d6](https://github.com/hh79/gzdoomvr/assets/96748149/6c08457c-56a4-4474-b3cb-9da3abea7160)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

**Comment by BigheadSMZ** [comment]
I'm having the same issue. I can't get it to output video no matter what I try. I can hear the sounds on my quest 3, but the windows on my PC is black and the quest 3 is just showing the steam VR room like the screenshot above.

**Comment by Doomguyscaresme** [comment]
same bro

**Comment by BigheadSMZ** [comment]
Turns out it starts in Vulkan. Need to set the video mode to OpenGL for it to show up on the Quest 3.

**Comment by hh79** [comment]
If you are using a version older than 4.12.2, please select the OpenGL backend.
