### ISSUE TITLE
[Feature] GZ DOOM VR 4.12.2

### ISSUE THREAD

**Issue by ReverquestVR** [hh79/gzdoomvr#94]
### GZDoom version

GZ DOOM 4.11.3

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 11

### Relevant hardware info

rtx 4090 i7 13 generation

### Is your feature request related to a problem? Please describe.

Yes. Evirtenity 2 RC5 dont work GZ DOOM 4.11.3, needed 4.12.2 

### Describe the solution you'd like

Create GZ DOOM VR 4.12.2

**Comment by doomgtr** [comment]
+1

**Comment by Sho0Fly** [comment]
+1

D3.PK3 (doom 3 VR) does not work until GZDoomVR 4.12 or higher. Would love to see an update to 4.12.2 (or newer like 13!)

[Doom 3 (Doom II mod)](https://www.youtube.com/watch?v=SLxuku32ZDM) trailer

**Comment by hh79** [comment]
GZDoomVR was updated to 4.12.2. D3 seems to be working.
