### ISSUE TITLE
[BUG] WEAPONS ONLY WORK IN SPRITE MODE

### ISSUE THREAD

**Issue by MAXJ-afwef** [hh79/gzdoomvr#95]
### GZDoom version

GZDOOMVR 4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Weapons only work in sprite form.
Does not work on: Doom2 Vanilla, Project Brutality 3.0, Wolfenstein Blade of Agony, Brutal Doom V22 Test 3

TIP: Turn weapon scaling down to 0 and turn on the laser sight using the Laser-Sight-0.6.pk3 mod. With Project Brutality 3.0  that gets rid of the dancing legs and you can see what weapon you have selected with the ammo display, but aiming with a laser sight is extremely tragic. I would rather have a stick. or white bar. or anything at all to aim with with besides just sticking the laser pointer on the guys.

PS. I made a forum post for Doom 2 on Steam because GZDOOM 4.11.3 comes setup with switches turned on that cause it to simply not work. I found finding the answers to these questions so vague and scattered that I gave up on it for months before I finally realized I just had to change the Preferred Backend to open_gl. The hunting I had to do to realize the engine ships with a switch turned on that causes it to not work was tragic considering how awesome Project Brutality is in VR with all the sprites gibs, dripping ceilings and the wonderful imps that jump and pounce everywhere.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Switch the gun to any kind of display beside Sprite in VR options
2. Watch the game instantly crash or crash as soon as you approach the first weapons
3.

### Your configuration

```ini
Oh crap my ini is on another comp. I changed preferred backend to 0 and turned of Interpolated Rendering.
```

**Comment by BigheadSMZ** [comment]
Problem is the PK3 files. Grab the weapons files from an older version (like 4.8.2) and replace them in the newest version and they will work again. The current release version of GZDoomVR seems like a mess and really needs an update. This and it starting in Vulkan instead of OpenGL are pretty outstanding and breaking issues.

**Comment by hh79** [comment]
Only the Voxels Weapon Pack (WeaponsForVR.pk3) will work in newer versions. In version 4.12.2, the Vulkan backend is disabled by default.
